- README.md
- registry/identity_registration_data.go
Currently we only have OS X installation documentation in the
README. Solidity maintains their own installation docs for various
platforms as does Ethereum, we can use these.
Link to project docs for installation instructions.
Signed-off-by: Tobin C. Harding <me@tobin.cc>
> Link to project docs for installation

- Gopkg.lock
- Gopkg.toml
Bumping ethereum version to make node build on Go 1.12. Will need to tag and make the change in node repo.
> bump go-ethereum to 1.8.23

- crypto/crypto.go
- crypto/crypto_test.go
- crypto/invoice.go
- crypto/message.go
1) Renamed fee to transactor fee in invoice.
2) Accountant ID added to consumer channel address generation.
> Rename fee + Accountant ID in channel address generation

- client/client.go
- client/retryable_client.go
- client/with_dry_runs.go
Setting gas limits will make ethereum client skip dry runs. Added a client wrapper that forces such requests to perform a dry run before going to the network.
updates https://github.com/mysteriumnetwork/transactor/issues/21
> forced dry runs for transactions with gas limits

- bindings/estimator.go
- client/client.go
- client/retryable_client.go
- client/with_dry_runs.go
Updates: https://github.com/mysteriumnetwork/node/issues/2707
`WithDryRuns.Estimate()` simulates transaction in VM and estimates gas needed for it to execute
`WithDryRuns.DryRun()` simulates transaction in VM and returns smart contract thrown error (if any)
> Implement contract binding which estimates transaction execution

- fees/incrementor.go
- fees/incrementor_test.go
This was that when gas price limit was reached we would do one more spin for a transaction with no values at all.
This is now fixed.
> Fix: chain_id sometimes becomes zero

- client/retryable_client.go
retryable client was missing certain methods making it not fullfill the `BC` interface. in turn this made it impossible to use in other services like hermes.
> Fulfill BC interface in all clients

- fees/incrementor.go
- fees/incrementor_test.go
- fees/transaction.go
This fixes a problem where we would use the old hash after incrementing price once.
Closes: https://github.com/mysteriumnetwork/transactor/issues/208
> Use proper hash in gas incrementor

- client/bc.go
- client/client.go
- client/multichain_client.go
- client/retryable_client.go
- client/with_dry_runs.go
* Added a method to make custody token transfers
* Moved the `BC` interface to another file as it's always annoying to look for it somewhere random.
> Add interface methods for custody transfers

- fees/incrementor.go
- fees/incrementor_test.go
This allows us to error out when running multiple instances of service that uses incrementor and the same database.
Updates: https://github.com/mysteriumnetwork/transactor/issues/213
> Incrementor should only pick transactions it can actually sign

- fees/handler.go
- fees/incrementor.go
- fees/incrementor_test.go
* Check queue, if we have more than X amount of transactions - dont submit a new one.
* Validate transaction opts before submitting a transaction.
* Check if we have the sigenrs to repeat the transaction, if we dont - dont submit it.
Updates: https://github.com/mysteriumnetwork/transactor/issues/172
> Gas incrementor and transaction handler now queue

- client/ethclient.go
- client/ethclient_test.go
- client/retryable_client.go
Take note that this is not 100% bullet proof.
To make it bulletproof I'd need to wrap the following interface:
```
type bcc interface {
bind.ContractBackend
...
// some extra eth.client methods we're using
}
```
I don't think it's worth doing atm as this fix should solve 99% of the cases we encounter.
> No more races with client

- fees/gas/eth.go
Closes: https://github.com/mysteriumnetwork/transactor/issues/227
Judging from docs and the error received these values are floating point numbers: https://docs.defipulse.com/api-docs-by-provider/egs/gas-price
> Defipulse gas station use float64

- client/with_dry_runs.go
- transfer/incrementor.go
- transfer/incrementor_test.go
- transfer/transaction.go
* Remove the infinite goroutine spawning.
* Removed the syncer. Not needed anymore
* **Introduced new workflow:**
* Pull transactions from DB by two TS fields:
*  NextCheck + NextIncrease. Idea is to pull if either one is before time.Now.UTC().
* Spawn X amount of works who all do the same
* Always check if transaction was successful
* If NextIncrease is before time.Now.UTC() increase gas price
* **If check received `NotFound` still increase the gas price if time has passed.**
* This is a bit controversial.
Closes: https://github.com/mysteriumnetwork/payments/issues/123
> Incrementor remake

- transfer/gas/eth.go
- transfer/gas/etherscan.go
- transfer/gas/matic.go
- transfer/gas/multichain_station.go
- transfer/gas/static.go
- transfer/gas/station.go
The functions for getting the different prices (safeLow, average and fast) are now only one, as all API returns them all together. A refactor will be needed in other projects too.
Etherscan is added as an API provider for gas prices.
> Add etherscan and refactor stations for easier usage

- transfer/gas/multichain_station.go
- transfer/gas/multichain_station_test.go
Multiple stations are supported and prioritized in array order.
Also added tests.
Signed-off-by: Guillem <guillem@mysterium.network>
> Make multichainStation support multiple stations

- client/bc.go
A generic function to check if a call to blockchain failed or no response ever was received.
> Add a generic func to check if error is a failure to reach BC

- transfer/incrementor.go
Max price is OK if calculation fails, `nil` is not as at will auto suggest gas price which we cannot control.
> Do not default to `nil` if calculation fails

- client/bc.go
- client/client.go
- client/multichain_client.go
- client/with_dry_runs.go
Easier to work with block numbers in payment services if we have this here.
Dont have to carry two interfaces around.
> Add block number method to the interface

- client/client.go
- transfer/incrementor.go
- transfer/incrementor_test.go
* Client would sometimes pull nonce and sometimes use the given one. It should always use the given one if it exists. Race would happen like this:
* Send registration transaction with mutex nonce
* Send topup with nonce pulled from BC
* Pull the same nonce and fail everything
* Dont send transaction if it's already known, spamming is not cool.
> Fix: Dont resend if known and pull nonce only if unknown

- client/bc.go
- client/client.go
- client/multichain_client.go
- client/with_dry_runs.go
- transaction/courier/data.go
- transaction/courier/simple.go
- transaction/delivery.go
- transaction/depot.go
- transaction/gas/eth.go
- transaction/gas/etherscan.go
- transaction/gas/matic.go
- transaction/gas/multichain_station.go
- transaction/gas/multichain_station_test.go
- transaction/gas/static.go
- transaction/gas/station.go
- transaction/gas_tracker.go
- transaction/nonce_tracker.go
- transaction/sender.go
* Introduced a new package `transaction`. Old package `transfer` is left for compatability, but will be deleted after everyone upgrades.
* New package `transaction` provides the same `gas` station package to interect with gas stations.
* New package contains new logic for a transaction delivery on the blockchain:
* The base of all the logic is contained in the `delivery depot`. It works in a similar way as a real world delivery depot. Provided workers who package and track transactions and couriers which are able to deliver them, it's able to track transaction and delivery them.
* A basic `courier` is provided which is able to deliver MYST and ETH transactions. The given courier doesn't have to be used or it can get wrapped by other couriers in services if needed.
* Transactions are no …
> Remake transaction handling

- transaction/depot.go
If transactions have a lot of time between them, we should check for that and dont increment if not needed.
> Dont depend on last transaction delivered for fillup

- transaction/gas_tracker.go
If the lastKnown*mult is nil or is lower than the current gas price, we will return the current gas price. Will make gas recalculation more eficient.
> Return the max of current gas and lastKnown*mult

- transaction/depot.go
Leftover bug from upgrade to EIP-1559. We no longer use gas price, we use gas tips.
> Fix a gas price check for resending

- client/client.go
- client/hermes_caller.go
Main performance degradation happens not during RPC calls, but during instantiating new caller. Specifically during mapping ABI json metadata to ABI models (this json is quite big, around 16kb). There is no need to create new caller each time.
> Add registry to cache Hermes Callers

- transaction/gas/node_station.go
This GasStation does 3 calls to bc:
* **SuggestGasPrice** to receive gas price, calculated by geth client
* **BlockNumber** to get latest block number
* **HeaderByNumber** to get header of latest block
> Add gas station, that do call to bc to get suggested gas price

- observer/api.go
Instead of copying things everywhere, lets use one generic implementation.
Together with this I also added filtering support and removed not needed code.
> Make a generic observer package
