Gopkg.lock, Gopkg.toml, identity/keystore_signer_test.go, promises/promise.go, registry/keystore_identity_holder.go, registry/registry.go, test_utils/backend.go
This is a dependency for the following PR: https://github.com/MysteriumNetwork/node/pull/318
It created to resolve mutual dependencies.
=> Updated go-ethereum to 1.8.14

promises/clearing.go, promises/promise.go
=> int64 -> uint64 for promise seqNo and amount

crypto/message_test.go, crypto/promise.go, crypto/promise_test.go
This should also fix problems with creating provider channel promises. Previous implementation was creating not valid signatures because of doing `common.ToHexAddress(channelID)`. ChannelID depending on channel type may be 20 or 32 bytes.
Also covered promise creation with tests for consumer and provider promises.
=> Moving into better typed Promise format

crypto/promise.go, crypto/promise_test.go
=> Fixing bug with promise signature mutations 

client/client.go, go.mod, go.sum
The subscriptions would timeout causing issues. They are now using a resubscribe pattern, so that a resubscription attempt would be made in that case.
Updates https://github.com/mysteriumnetwork/node/issues/1458
=> sticky the subscriptions

client/tx_watcher.go
Will now retry the transaction a few times if it fails to appear on BC.
Closes #47
=> implemented transaction watcher

client/client.go, client/ethclient.go, client/ethclient_test.go
https://github.com/mysteriumnetwork/node/issues/1944
=> Add reconnactable ethereum client

client/client.go
For identity registration we will store nonce to be able to retry with higher price.
=> Allow to pass nonce for registration

crypto/crypto_test.go, crypto/message.go, crypto/message_test.go
Closes https://github.com/mysteriumnetwork/node/issues/2216
=> Extend the exchange message with hermes ID

bindings/abi/abigen.go, bindings/topics.go, crypto/exit.go
Prereq for hermes to listen for exit request.
=> Exit request

client/client.go, client/multichain_client.go, client/retryable_client.go, client/with_dry_runs.go, fees/handler.go, fees/incrementor.go, fees/incrementor_test.go, fees/transaction.go, fees/watcher.go
Initial implementation of gas price incrementor. Tests coverage will be done after everything is set in stone.
Notable changes:
* Introduced a new gas price incrementor
* Moved TxWatcher to a new `fees` package
* Introduced a wrapper for both the TxWatcher and Incrementor for easy reuse.
Closes: https://github.com/mysteriumnetwork/transactor/issues/111
=> Introduce gas price incrementer

fees/gas/eth.go, fees/gas/matic.go, fees/gas/static.go, fees/gas/station.go, units/units.go
Moved units and gas stations from transactor
=> Gas stations

fees/gas/static.go
Fixed static gas station so the it fits the interface
=> Static gas price fix

client/ethclient.go
If no context is passed dial just hangs.
Closes: https://github.com/mysteriumnetwork/payments/issues/108
=> Eth dial calls should always timeout

transfer/multichain_queue.go, transfer/multichain_queue_test.go
Created multichain queues to maximize the throughput of the transactions. #119 
Signed-off-by: Guillem <guillem@mysterium.network>
=> Created multichain queue

crypto/helpers.go, crypto/helpers_test.go, go.mod, go.sum
Updates: https://github.com/mysteriumnetwork/pilvytis/issues/310
=> Accurate conversions between Big and Decimal types

transfer/handler.go
Nonce should be unique per chain.
=> Nonce should be unique per chain

transaction/depot.go, transaction/nonce_tracker.go
* If entry fails to insert in to DB, dont increment nonce for other deliveries
* Have a max queue size for a sender. If we're failing to delivered it's better to stop inserting new entries than dealing with a 10k long queue later.
=> Update Depot logic

transaction/depot.go
- If we aren't sure if the transaction was sent, reset it's gas price and resend it again.
- Fixed a bug that would make depot panic if no logger was attached
- Shortened and moved the arbitrary wait time between resends only for packing transaction as it's not longer needed for others because of this previous PR: https://github.com/mysteriumnetwork/payments/pull/163
=> Resend transaction if it's in state packing

transaction/depot.go, transaction/gas_tracker.go
Added logic to resend transactions which were send, reached max gas price but never appeared on BC. Also made gas price assigning a bit easier to read.
Closes:
* https://github.com/mysteriumnetwork/node/issues/4599
* https://github.com/mysteriumnetwork/node/issues/4597
=> Resend transactions which were sent but don't appear in BC

transaction/depot.go, transaction/metrics.go
Should be enough to report latest nonces for transactions and queue size.
Relates to: https://github.com/mysteriumnetwork/transactor/issues/345
=> Add metrics iface

transaction/gas/polygonscan.go
Closes: https://github.com/mysteriumnetwork/payments/issues/168
=> Add polygonscan gas station

client/bc.go, client/client.go, client/multichain_client.go, client/with_dry_runs.go
Using these swapping and simple pool exploring is now possible.
Updates: https://github.com/mysteriumnetwork/node/issues/4549
=> Add all methods required to do simple swapping

client/client.go, transaction/delivery.go, transaction/depot.go, transaction/gas/etherscan.go, transaction/gas/polygon_official.go, transaction/gas/polygonscan.go, transaction/gas/static.go, transaction/gas/station.go, transaction/gas_tracker.go
Allow the ability to also set `GasFeeCap` so that we're sure we're not overpaying and dont have to rely on oracles.
=> Use the base price too

transaction/depot.go
Queue even if the queue is full
=> Allow to force queue if needed

README.md, bindings/README.md, client/README.md, crypto/README.md, exchange/README.md, merkle/README.md, registration/README.md, transaction/README.md, transaction/gas/README.md, transfer/README.md, units/README.md
yay, [docs](https://github.com/mysteriumnetwork/payments/blob/improve-docs/README.md)! <-click to read them
Closes: #182 
=> Impove payments docs

units/units.go
=> float eth to big int wei

gen.go
Easy generation for the future
=> Update version of payments

client/bc.go, client/client.go, client/multichain_client.go, client/with_dry_runs.go
=> add call to get hermes registry from hermes id

client/addresses.go
- Address keeper now distinguishes has a known hermeses list hermeses and is able to have an active one.
- Address provider is able to generate a channel address given a Hermes address.
Would it be worth adding a check that iterates the addresses map and checks that for each chain the active hermes is also in the hermeses list? or should the list not include it and be returned in `getKnownHermeses`
=> add list of hermeses, and generate channel by hermes to address keeper

client/client.go, registration/registration.go
Rename OpenChannel to OpenConsumerChannel
Fix OpenConsumerChannel ABI
=> Fix open consumer channel

registration/registration.go
Signed-off-by: AndreyM <andrey@mysterium.network>
=> Add registry address to signature calculation

client/bc.go, client/client.go, client/multichain_client.go, client/with_dry_runs.go
Signed-off-by: AndreyM <andrey@mysterium.network>
=> Add filter to track Hermes URL change event

observer/api.go
Relates to: https://github.com/mysteriumnetwork/payments/issues/211
=> Extend generic observer

observer/api.go
=> get hermes addresses by query

transaction/depot.go, transaction/depot_test.go, transaction/gas_tracker.go
Test coverage of `/transaction` goes from `4.5%` to `57.5%`
=> add all tests to depot

go.mod, go.sum, utils/set.go, utils/set_test.go
=> add set to new utils package

.github/CODEOWNERS, utils/set.go
=> add set conversion funcs

.github/workflows/generate.yml, .github/workflows/test.yml, client/ethclient_test.go, client/ethmulticlient.go, client/ethmulticlient_test.go, go.mod
=> tests for ethclient and ethmulticlient

client/adresses_test.go, client/bc.go, client/bc_test.go, client/client.go, client/client_test.go, client/ethmulticlient_test.go, client/hermes_caller.go, client/hermes_caller_test.go, client/with_dry_runs.go, crypto/beneficiary.go, crypto/beneficiary_test.go, crypto/crypto.go, crypto/crypto_test.go, crypto/exit.go, crypto/exit_test.go, crypto/helpers.go, crypto/helpers_test.go, crypto/invoice.go, crypto/message_test.go, crypto/old_units.go, crypto/payandsettle.go, crypto/payandsettle_test.go, crypto/promise.go, crypto/promise_test.go, crypto/stake.go, crypto/stake_test.go, units/README.md, units/units.go, units/units_test.go
=> add more test in client

units/units.go, units/units_test.go
=> add used functions as deprecated

transaction/depot.go
Also return more meaningful errors
=> fix bug not able to resend

transaction/depot_test.go
Test [fails](https://github.com/mysteriumnetwork/payments/actions/runs/3428656973/jobs/5713232264) randomly
```
WARNING: DATA RACE
Read at 0x00c0001ef180 by goroutine 61:
github.com/mysteriumnetwork/payments/transaction.TestDepot.func4.3.2.1()
/home/runner/work/payments/payments/transaction/depot_test.go:418 +0xba
github.com/stretchr/testify/assert.Eventually.func1()
/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:1691 +0x39
Previous write at 0x00c0001ef180 by goroutine 12:
github.com/mysteriumnetwork/payments/transaction.(*mockStorage).UpsertDeliveryRequest()
/home/runner/work/payments/payments/transaction/depot_test.go:540 +0x30d
github.com/mysteriumnetwork/payments/transaction.(*Depot).markDeliveryAsDelivered() …
```
=> Fix race condition bug

client/with_dry_runs.go, test/channel.go, test/channel_test.go, test/common.go, test/common_test.go, test/docker-compose.yml, test/hermes.go, test/hermes_test.go, test/registry.go, test/registry_test.go, test/token.go, test/token_test.go
We are using this kind of functions in many e2e tests in other project, to me it makes sense to simplify them and have them in one place.
=> Testing sdk
